	SUBROUTINE MEANRMS(A,RMS,AMEAN,NP)
C	TO COMPUTE MEAN AND RMS OF 'A' BY EXCLUDING WHAT MAY BE
C	SOME CONTRIBUTION FROM INTERFERENCE
C
	DIMENSION A(*)
C
	ITER=0
C
101	ITER=ITER+1
	AMEAN=0.0
	AN=0.0
C
	DO I=1,NP
	IF(ITER.EQ.1)GO TO 1
	DIFF=ABS(A(I)-AMEAN0)
	IF(DIFF.LE.(4.*RMS))GO TO 1
	GO TO 2
1	AMEAN=A(I)+AMEAN
	AN=AN+1.
2	CONTINUE
	END DO
C
	RMS0=RMS
	if(an.gt.0)AMEAN=AMEAN/AN
C
	RMS=0.0
	AN=0.0
	DO I=1,NP
	DIFF=ABS(A(I)-AMEAN)
	IF(ITER.EQ.1)GO TO 11
	IF(DIFF.LE.(4.*RMS0))GO TO 11
	GO TO 12
11	RMS=RMS+DIFF*DIFF
	AN=AN+1.
12	CONTINUE
	END DO
C
	if(an.gt.0.0)RMS=SQRT(RMS/AN)
	AMEAN0=AMEAN

	IF(ITER.EQ.1)GO TO 101
        if(rms.eq.0.0)return
	IF(ABS((RMS0/RMS)-1.).GT.0.05)GO TO 101
	RETURN
	END

